Fix "inp" variable collission with mingw
Builds for Windows were throwing an error to the tune of: "32blit-beta/32blit-sdl/Main.cpp:29:8: error: ‘Input* inp’ redeclared as different kind of symbol"

This is because mingw's intrin.h defines `int inp(short unsigned int)`, which was clashing with our variable name.

I've disambiguated the somewhat risky 3-letter variable names to blit_input, blit_system, blit_renderer and blit_capture to avoid any future clashes or confusion.